version: '3.8'

services:
  api:
    image: ani31415/bike-sharing-api:latest
    container_name: bike-sharing-container
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: bike-sharing-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"